#!/usr/bin/env python

from simple_grasping_action.simple_grasping_action import SimpleGraspingAction
import rospy

def main():
    rospy.init_node('simple_grasping_action')
    try:
        controller = SimpleGraspingAction(rospy.get_name())
    except Exception as e:
        rospy.logfatal('Caught unexpected exception. ' + str(e))
    except:
        rospy.logfatal('Caught unexpected exception.')
    rospy.spin()

if __name__ == '__main__':
    main()
